name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: MSBuild xbox-winfsp.sln /p:Configuration=Release

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp build/Release/xbox-winfsp.exe build/Release/winfsp-msil.dll dist/_INSTALL.bat dist/_UNINSTALL.bat README.md artifacts
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xbox-winfsp.Release
          path: artifacts
          if-no-files-found: error
