name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: msbuild xbox-winfsp.sln /m /p:Configuration=${{ matrix.configuration }}

      - name: Prepare artifacts
        if: matrix.configuration == 'Release'
        run: |
          mkdir -p artifacts
          cp build/${{ matrix.configuration }}/{xbox-winfsp.exe,winfsp-msil.dll} dist/_{,UN}INSTALL.bat README.md artifacts
        shell: bash

      - name: Upload artifacts
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v2
        with:
          name: xbox-winfsp.${{ matrix.configuration }}
          path: artifacts
          if-no-files-found: error
